server:
  port: 8081
  servlet:
    context-path: /nexawork-auth-api-v1

spring:
  application:
    name: nexawork-auth
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:nexawork_auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passe}
  flyway:
    locations: classpath:db/migration

nexawork:
  jwt:
    refresh-token-validity-in-days: 7

management:
  health:
    group:
      readiness:
        include: "readinessState,db,rabbit"
