server:
  port: 8083
  servlet:
    context-path: /nexawork-messaging-api-v1

spring:
  application:
    name: nexawork-messaging
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:nexawork_messaging_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passe}
  flyway:
    locations: classpath:db/migration

management:
  health:
    group:
      readiness:
        include: "readinessState,db,rabbit"
