server:
  port: 8084
  servlet:
    context-path: /nexawork-meeting-api-v1

spring:
  application:
    name: nexawork-meeting
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:nexawork_meeting_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:passe}
  flyway:
    locations: classpath:db/migration

management:
  health:
    group:
      readiness:
        include: "readinessState,db,rabbit"

nexawork:
  jaas:
    app-id: ${JAAS_APP_ID:vpaas-magic-cookie-changeme}
    api-key-id: ${JAAS_API_KEY_ID:changeme/changeme}
    private-key: ${JAAS_PRIVATE_KEY:}
    url: https://8x8.vc
